name: Generate Snake Game from Contributions

on:
  workflow_dispatch:

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: platane/snk@v3  # Replace 'v1.0' with the actual version tag available.
        with:
          github_user_name: 'Sabbir-Hossain22'
            
