name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Run every 12 hours
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Also run on every push on the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Sabbir-Hossain22  # Your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # Your secret token stored as ACTIONS_DEPLOY_KEY

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Specify the branch where the files will be pushed
          build_dir: dist  # Directory with generated files
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # Use the same secret token to push files

      - name: Debug output
        run: |
          ls -la dist
          cat dist/github-contribution-grid-snake.svg
          cat dist/github-contribution-grid-snake-dark.svg
          cat dist/github-contribution-grid-snake.gif
